### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

In [2]:
import numpy as np

###### 1. Write a NumPy program to find the missing data in a given array.

In [27]:
x=np.array([[3,2,np.nan,1],[10,12,10,9],[5,np.nan,1,np.nan]],dtype=float)
print("Original array:\n",x)
print("\nFind the missing data of the said array:\n",np.isnan(x))

Original array:
 [[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
 [[False False  True False]
 [False False False False]
 [False  True False  True]]


##### 2. Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [6]:
x1=np.array([1,2,3,4,5])
x2=np.array([1,2,3,4,5])
x1==x2

array([ True,  True,  True,  True,  True])

###### 3. Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [26]:
y=np.arange(0,16,1).reshape(4,4)
print("Original array:\n",y)
print("\nNew array after swapping first and last rows of the said array:\n",y[::-1])

Original array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
 [[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


###### 4. Write a NumPy program to convert a list and tuple into arrays.

In [12]:
z1=[1,2,3,4,5]
print("Program to convert a list into arrays:\n",np.array(z1))
z2=(6,7,8,9,10)
print("Program to convert a tuple into arrays:\n",np.array(z2))

Program to convert a list into arrays:
 [1 2 3 4 5]
Program to convert a tuple into arrays:
 [ 6  7  8  9 10]


###### 5. Write a NumPy program to find common values between two arrays.

In [33]:
s=np.array([1,2,3,4,5])
print("Array-1:\n",s)
t=np.array([11,2,13,4,15])
print("Array-2:\n",t)
print("Common values between two arrays:\n",np.intersect1d(s,t))

Array-1:
 [1 2 3 4 5]
Array-2:
 [11  2 13  4 15]
Common values between two arrays:
 [2 4]


###### 6. Write a NumPy program to create a new shape to an array without changing its data.

In [17]:
a=np.arange(1,7,1).reshape(3,2)
print("Reshape 3x2:\n",a)
a=a.T
print("Reshape 2x3:\n",a)

Reshape 3x2:
 [[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
 [[1 3 5]
 [2 4 6]]


###### 7. Write a NumPy program to count the frequency of unique values in numpy array.

In [20]:
b=[10,10,20,10,20,20,20,30,30,50,40,40]
print("Original array:\n",b)
b1=np.unique(b,return_counts=True)
print("Frequency of unique values of the said array:\n",b1)

Original array:
 [10, 10, 20, 10, 20, 20, 20, 30, 30, 50, 40, 40]
Frequency of unique values of the said array:
 (array([10, 20, 30, 40, 50]), array([3, 4, 2, 2, 1], dtype=int64))


###### 8. Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).

In [25]:
p=np.array([[0,0,0],[1,2,3],[4,5,6]])
print("Original arrays:\n","Array-1:\n",p)
q=np.array([10,11,12])
print("Array-2:\n",q)
print("\nNew Array:\n",p+q)

Original arrays:
 Array-1:
 [[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2:
 [10 11 12]

New Array:
 [[10 11 12]
 [11 13 15]
 [14 16 18]]


###### 9. Write a NumPy program to extract all the elements of the second row from a given (4x4) array.

In [24]:
import numpy as np
arra_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Second row")
print(arra_data[1,:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


###### 10. Write a NumPy program to extract third and fourth elements of the first and second rows from a given (4x4) array.

In [28]:
w=np.arange(0,16,1).reshape(4,4)
print("Original array:\n",w)
print("\nExtracted data: Third and fourth elements of the first and second rows:\n",w[0:2,2:])

Original array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows:
 [[2 3]
 [6 7]]


###### 11. Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [35]:
yesterday=np.datetime64("today","D")-np.timedelta64(1,"D")
print("yesterday:",yesterday)
today=np.datetime64("today","D")
print("today:",today)
tomorrow=np.datetime64("today","D")+np.timedelta64(1,"D")
print("tomorrow:",tomorrow)

yesterday: 2022-09-09
today: 2022-09-10
tomorrow: 2022-09-11


###### 12. Write a NumPy program to find the first Monday in May 2017.

In [40]:
import numpy
yearMonth="2017-05"
date=numpy.busday_offset(yearMonth,0,roll="forward",weekmask="Mon")
print(date)

2017-05-01
