### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

In [2]:
import numpy as np

#####1.  Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [8]:
x=np.zeros((10,))
print("An array of 10 zeros:\n",x)
y=np.ones((10,))
print("An array of 10 ones:\n",y)
z=np.full((10,),5,dtype=float)
print("An array of 10 fives:\n",z)

An array of 10 zeros:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#####2.  Write a NumPy program to create an array of the integers from 30 to 70.

In [16]:
a=np.arange(30,71,1)
print("Array of the integers from 30 to70:\n",a)

Array of the integers from 30 to70:
 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


######3. Write a NumPy program to create an array of all the even integers from 10 to 50.

In [17]:
b=np.arange(10,50,2)
print("Array of all the even integers from 10 to 50:\n",b)

Array of all the even integers from 10 to 50:
 [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


######4. Write a NumPy program to create a 3x3 identity matrix.

In [18]:
c=np.eye(3)
print("3x3 matrix:\n",c)

3x3 matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### 5. Write a NumPy program to generate a random number between 0 and 1

In [23]:
d=np.random.random((1,))
print("Random number between 0 and 1:\n",d)

Random number between 0 and 1:
 [0.33150968]


###### 6. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [25]:
e=np.random.random((15,))
print("15 random numbers from a standard normal distribution:\n",e)

15 random numbers from a standard normal distribution:
 [0.46879632 0.92313555 0.16749379 0.54161467 0.87558403 0.23205264
 0.97622778 0.10735915 0.70698104 0.79714693 0.26106858 0.57874405
 0.61253921 0.64887688 0.1308899 ]


###### 7. Write a NumPy program to create a 3X4 array using and iterate over it.

In [39]:
f=np.arange(10,22).reshape(3,4)
print("Original array:\n",f)
print("Each element of the array is:")
for y in f:
    for z in y:
        print(z,end=" ")        

Original array:
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

###### 8. Write a NumPy program to multiply the values ​​of two given vectors.

In [41]:
x1=np.array([1,8,3,5])
print("Vector-1:\n",x1)
x2=np.array([10,1,4,10])
print("Vector-2:\n",x2)
x3=np.multiply(x1,x2)
print("Multiply the values of two said vectors:\n",x3)

Vector-1:
 [1 8 3 5]
Vector-2:
 [10  1  4 10]
Multiply the values of two said vectors:
 [10  8 12 50]


###### 9. Write a NumPy program to reverse an array (first element becomes last).

In [66]:
p=np.arange(12,38,1)
print("Original array:\n",p)
print("Reverse array:\n",p[::-1])

Original array:
 [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
 [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


##### 10. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [67]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

###### 11. Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

In [61]:
z1=np.arange(0,4).reshape(2,2)
print("Original array:\n",z1)
print("Sum of all elements:\n",np.sum(z1))
a=np.sum(z1,axis=0)
print("Sum of each column:\n",a)
b=np.sum(z1,axis=1)
print("Sum of each row:\n",b)

Original array:
 [[0 1]
 [2 3]]
Sum of all elements:
 6
Sum of each column:
 [2 4]
Sum of each row:
 [1 5]


###### 12. Write a NumPy program to compute the inner product of two given vectors.

In [50]:
print("Original vectors:\n")
y1=np.array([4,5])
print(y1)
y2=np.array([7,10])
print(y2)
y3=np.dot(y1,y2)
print("Inner product of said vectors:\n",y3)

Original vectors:

[4 5]
[ 7 10]
Inner product of said vectors:
 78
