In [1]:
pip install opencv-python

In [1]:
import cv2
import numpy as np
import pandas as pd

In [2]:
import os

In [ ]:
os.mkdir(r"C:\Users\SSS\Desktop\opencv_task")  # make directory to create folder

In [ ]:
for y in range(1,6):
    os.mkdir(r"C:\Users\SSS\Desktop\opencv_task\{}".format(y))  # here i created 5 folder

In [4]:
os.getcwd()    # default path

'C:\\Users\\SSS'

In [3]:
os.chdir(r"C:\Users\SSS\Desktop\opencv_task")  # i need to change the directory where opencv_task folder present

In [4]:
os.getcwd()

'C:\\Users\\SSS\\Desktop\\opencv_task'

In [7]:
os.listdir()

['1', '2', '3', '4', '5']

In [14]:
vid=cv2.VideoCapture(0)
count=0
while True:
    count=count+1
    su,img=vid.read()
    if su==True:
        cv2.imshow("video",img)
        images=cv2.imwrite(r"C:\Users\SSS\Desktop\opencv_task\1\{}.jpg".format(count),img)

    if cv2.waitKey(1)==ord("q"):
        break
cv2.destroyAllWindows()

vi-have video object(frame),have attribute read() waitkey always have -1 if u dont press key that'swhy waitkey(1)==ord("q")

In [7]:
os.chdir(r"C:\Users\SSS\Desktop\opencv_task\1")

In [8]:
images=os.listdir()
images

['320.jpg',
 '321.jpg',
 '322.jpg',
 '323.jpg',
 '324.jpg',
 '325.jpg',
 '326.jpg',
 '327.jpg',
 '328.jpg',
 '329.jpg',
 '330.jpg',
 '331.jpg',
 '332.jpg',
 '333.jpg',
 '334.jpg',
 '335.jpg',
 '336.jpg',
 '337.jpg',
 '338.jpg',
 '339.jpg',
 '340.jpg',
 '341.jpg',
 '353.jpg',
 '354.jpg',
 '355.jpg',
 '356.jpg',
 '357.jpg',
 '358.jpg',
 '359.jpg',
 '360.jpg',
 '361.jpg',
 '362.jpg',
 '363.jpg',
 '364.jpg',
 '365.jpg',
 '366.jpg',
 '367.jpg',
 '368.jpg',
 '369.jpg',
 '370.jpg',
 '371.jpg',
 '372.jpg',
 '373.jpg',
 '374.jpg',
 '375.jpg',
 '376.jpg',
 '377.jpg',
 '378.jpg',
 '379.jpg',
 '380.jpg',
 '381.jpg',
 '382.jpg',
 '383.jpg',
 '384.jpg',
 '385.jpg',
 '386.jpg',
 '387.jpg',
 '388.jpg',
 '389.jpg',
 '390.jpg',
 '391.jpg',
 '392.jpg',
 '393.jpg',
 '394.jpg',
 '395.jpg',
 '396.jpg',
 '397.jpg',
 '398.jpg',
 '399.jpg',
 '400.jpg',
 '401.jpg',
 '402.jpg',
 '403.jpg',
 '404.jpg',
 '405.jpg',
 '406.jpg',
 '407.jpg',
 '408.jpg',
 '409.jpg',
 '410.jpg',
 '411.jpg',
 '412.jpg',
 '413.jpg',
 '41

In [10]:
img1=[]
for i in images:
    img1.append(cv2.imread(r"C:\Users\SSS\Desktop\opencv_task\1\{}".format(i)).flatten())
    data_one=pd.DataFrame({'array':img1,'label':1})
img1    

[array([173, 159, 160, ...,  12,  11,  31], dtype=uint8),
 array([173, 159, 160, ...,  12,  11,  31], dtype=uint8),
 array([173, 159, 160, ...,  12,  11,  31], dtype=uint8),
 array([174, 159, 156, ...,   0,   6,  13], dtype=uint8),
 array([174, 159, 156, ...,   0,   6,  13], dtype=uint8),
 array([174, 159, 156, ...,   0,   6,  13], dtype=uint8),
 array([171, 160, 163, ...,  16,   9,  30], dtype=uint8),
 array([171, 160, 163, ...,  16,   9,  30], dtype=uint8),
 array([171, 160, 163, ...,  16,   9,  30], dtype=uint8),
 array([173, 161, 161, ...,   5,  12,  27], dtype=uint8),
 array([173, 163, 163, ...,   9,  12,  27], dtype=uint8),
 array([169, 166, 158, ...,   4,  10,  29], dtype=uint8),
 array([169, 166, 158, ...,   4,  10,  29], dtype=uint8),
 array([169, 166, 158, ...,   4,  10,  29], dtype=uint8),
 array([169, 166, 158, ...,   4,  10,  29], dtype=uint8),
 array([169, 165, 164, ...,  15,  15,  29], dtype=uint8),
 array([171, 167, 166, ...,  12,  15,  29], dtype=uint8),
 array([171, 1

In [11]:
data_one

array  label
0    [173, 159, 160, 174, 160, 161, 174, 161, 163, ...      1
1    [173, 159, 160, 174, 160, 161, 174, 161, 163, ...      1
2    [173, 159, 160, 174, 160, 161, 174, 161, 163, ...      1
3    [174, 159, 156, 175, 160, 157, 173, 161, 155, ...      1
4    [174, 159, 156, 175, 160, 157, 173, 161, 155, ...      1
..                                                 ...    ...
151  [167, 160, 151, 167, 160, 151, 167, 160, 151, ...      1
152  [173, 160, 152, 173, 160, 152, 172, 159, 151, ...      1
153  [173, 160, 152, 173, 160, 152, 172, 159, 151, ...      1
154  [173, 160, 152, 173, 160, 152, 172, 159, 151, ...      1
155  [177, 161, 148, 177, 161, 148, 177, 161, 148, ...      1

[156 rows x 2 columns]

In [8]:
vid=cv2.VideoCapture(0)
count=0
while True:
    count=count+1
    su,img=vid.read()
    if su==True:
        cv2.imshow("video",img)
        images=cv2.imwrite(r"C:\Users\SSS\Desktop\opencv_task\2\{}.jpg".format(count),img)

    if cv2.waitKey(1)==ord("q"):
        break
cv2.destroyAllWindows()

In [6]:
os.chdir(r"C:\Users\SSS\Desktop\opencv_task\2")
img2=[]
for i in os.listdir():
    img2.append(cv2.imread(r"C:\Users\SSS\Desktop\opencv_task\2\{}".format(i)).flatten())
    data_two=pd.DataFrame({'array':img2,'label':2})
img2  

[array([211, 199, 193, ...,   0,   0,   1], dtype=uint8),
 array([211, 199, 193, ...,   0,   0,   1], dtype=uint8),
 array([211, 196, 187, ...,   0,   1,   0], dtype=uint8),
 array([211, 196, 187, ...,   0,   1,   0], dtype=uint8),
 array([211, 196, 187, ...,   0,   1,   0], dtype=uint8),
 array([204, 197, 194, ...,   2,   0,   0], dtype=uint8),
 array([204, 197, 194, ...,   2,   0,   0], dtype=uint8),
 array([204, 197, 194, ...,   2,   0,   0], dtype=uint8),
 array([205, 194, 190, ...,   0,   0,   0], dtype=uint8),
 array([205, 194, 190, ...,   0,   0,   0], dtype=uint8),
 array([205, 194, 190, ...,   0,   0,   0], dtype=uint8),
 array([206, 200, 195, ...,   0,   0,   0], dtype=uint8),
 array([206, 200, 195, ...,   0,   0,   0], dtype=uint8),
 array([206, 200, 195, ...,   0,   0,   0], dtype=uint8),
 array([214, 199, 197, ...,   0,   0,   0], dtype=uint8),
 array([214, 199, 197, ...,   0,   0,   0], dtype=uint8),
 array([214, 199, 197, ...,   0,   0,   0], dtype=uint8),
 array([208, 1

In [7]:
data_two

array  label
0   [211, 199, 193, 211, 199, 193, 207, 196, 192, ...      2
1   [211, 199, 193, 211, 199, 193, 207, 196, 192, ...      2
2   [211, 196, 187, 211, 196, 187, 208, 195, 187, ...      2
3   [211, 196, 187, 211, 196, 187, 208, 195, 187, ...      2
4   [211, 196, 187, 211, 196, 187, 208, 195, 187, ...      2
..                                                ...    ...
77  [211, 201, 194, 210, 200, 193, 209, 197, 195, ...      2
78  [217, 197, 196, 217, 197, 196, 217, 197, 196, ...      2
79  [217, 197, 196, 217, 197, 196, 217, 197, 196, ...      2
80  [217, 197, 196, 217, 197, 196, 217, 197, 196, ...      2
81  [209, 197, 195, 210, 198, 196, 209, 197, 197, ...      2

[82 rows x 2 columns]

In [8]:
vid=cv2.VideoCapture(0)
count=0
while True:
    count=count+1
    su,img=vid.read()
    if su==True:
        cv2.imshow("video",img)
        images=cv2.imwrite(r"C:\Users\SSS\Desktop\opencv_task\3\{}.jpg".format(count),img)

    if cv2.waitKey(1)==ord("q"):
        break
cv2.destroyAllWindows()

In [7]:
os.chdir(r"C:\Users\SSS\Desktop\opencv_task\3")
img3=[]
for i in os.listdir():
    img3.append(cv2.imread(r"C:\Users\SSS\Desktop\opencv_task\3\{}".format(i)).flatten())
    data_three=pd.DataFrame({'array':img3,'label':3})
img3  

[array([217, 198, 195, ...,   0,   0,   3], dtype=uint8),
 array([217, 198, 195, ...,   0,   0,   3], dtype=uint8),
 array([212, 198, 199, ...,   0,   1,   0], dtype=uint8),
 array([212, 198, 199, ...,   0,   1,   0], dtype=uint8),
 array([212, 198, 199, ...,   0,   1,   0], dtype=uint8),
 array([219, 199, 188, ...,   0,   0,   3], dtype=uint8),
 array([219, 199, 188, ...,   0,   0,   3], dtype=uint8),
 array([219, 199, 188, ...,   0,   0,   3], dtype=uint8),
 array([212, 199, 191, ...,   0,   0,   0], dtype=uint8),
 array([212, 199, 191, ...,   0,   0,   0], dtype=uint8),
 array([212, 199, 191, ...,   0,   0,   0], dtype=uint8),
 array([213, 194, 189, ...,   0,   0,   0], dtype=uint8),
 array([213, 194, 189, ...,   0,   0,   0], dtype=uint8),
 array([213, 194, 189, ...,   0,   0,   0], dtype=uint8),
 array([217, 198, 190, ...,   0,   0,   0], dtype=uint8),
 array([217, 198, 190, ...,   0,   0,   0], dtype=uint8),
 array([217, 198, 190, ...,   0,   0,   0], dtype=uint8),
 array([211, 1

In [8]:
data_three

array  label
0   [217, 198, 195, 217, 198, 195, 214, 196, 195, ...      3
1   [217, 198, 195, 217, 198, 195, 214, 196, 195, ...      3
2   [212, 198, 199, 211, 197, 198, 211, 195, 196, ...      3
3   [212, 198, 199, 211, 197, 198, 211, 195, 196, ...      3
4   [212, 198, 199, 211, 197, 198, 211, 195, 196, ...      3
5   [219, 199, 188, 219, 199, 188, 217, 198, 190, ...      3
6   [219, 199, 188, 219, 199, 188, 217, 198, 190, ...      3
7   [219, 199, 188, 219, 199, 188, 217, 198, 190, ...      3
8   [212, 199, 191, 211, 198, 190, 208, 196, 190, ...      3
9   [212, 199, 191, 211, 198, 190, 208, 196, 190, ...      3
10  [212, 199, 191, 211, 198, 190, 208, 196, 190, ...      3
11  [213, 194, 189, 211, 195, 189, 210, 194, 188, ...      3
12  [213, 194, 189, 211, 195, 189, 210, 194, 188, ...      3
13  [213, 194, 189, 211, 195, 189, 210, 194, 188, ...      3
14  [217, 198, 190, 217, 198, 190, 216, 197, 190, ...      3
15  [217, 198, 190, 217, 198, 190, 216, 197, 190, ...      3
16  [217, 198, 190, 217, 198, 190, 216, 197, 190, ...      3
17  [211, 199, 189, 209, 197, 187, 205, 195, 185, ...      3
18  [211, 199, 189, 209, 197, 187, 205, 195, 185, ...      3
19  [211, 199, 189, 209, 197, 187, 205, 195, 185, ...      3
20  [207, 198, 184, 205, 196, 182, 205, 193, 181, ...      3
21  [207, 198, 184, 205, 196, 182, 205, 193, 181, ...      3
22  [207, 198, 184, 205, 196, 182, 205, 193, 181, ...      3
23  [206, 197, 187, 205, 196, 186, 203, 195, 182, ...      3
24  [206, 197, 187, 205, 196, 186, 203, 195, 182, ...      3
25  [207, 201, 188, 204, 198, 185, 202, 196, 185, ...      3
26  [207, 201, 188, 204, 198, 185, 202, 196, 185, ...      3
27  [207, 201, 188, 204, 198, 185, 202, 196, 185, ...      3
28  [202, 198, 180, 200, 196, 178, 200, 194, 175, ...      3
29  [202, 198, 180, 200, 196, 178, 200, 194, 175, ...      3
30  [145, 137, 138, 145, 137, 138, 147, 136, 138, ...      3
31  [146, 138, 131, 145, 137, 130, 144, 136, 129, ...      3
32  [146, 138, 131, 145, 137, 130, 144, 136, 129, ...      3
33  [146, 138, 131, 145, 137, 130, 144, 136, 129, ...      3
34  [155, 145, 145, 154, 142, 140, 152, 140, 136, ...      3
35  [82, 66, 67, 80, 64, 65, 76, 57, 60, 72, 52, 5...      3
36  [82, 66, 67, 80, 64, 65, 76, 57, 60, 72, 52, 5...      3
37  [82, 66, 67, 80, 64, 65, 76, 57, 60, 72, 52, 5...      3
38  [64, 52, 50, 60, 50, 50, 58, 47, 49, 55, 45, 5...      3
39  [64, 52, 50, 60, 50, 50, 58, 47, 49, 55, 45, 5...      3
40  [64, 52, 50, 60, 50, 50, 58, 47, 49, 55, 45, 5...      3
41  [51, 50, 54, 52, 51, 53, 51, 49, 49, 51, 48, 4...      3
42  [89, 79, 79, 89, 79, 79, 89, 79, 79, 88, 78, 7...      3
43  [89, 79, 79, 89, 79, 79, 89, 79, 79, 88, 78, 7...      3
44  [89, 79, 79, 89, 79, 79, 89, 79, 79, 88, 78, 7...      3

In [ ]:
os.chdir(r"C:\Users\SSS\Desktop\opencv_task\4")
vid=cv2.VideoCapture(0)
count=0
while True:
    count=count+1
    su,img=vid.read()
    if su==True:
        cv2.imshow("video",img)
        images=cv2.imwrite(r"C:\Users\SSS\Desktop\opencv_task\4\{}.jpg".format(count),img)

    if cv2.waitKey(1)==ord("q"):
        break
cv2.destroyAllWindows()

In [7]:
os.chdir(r"C:\Users\SSS\Desktop\opencv_task\4")
img4=[]
for i in os.listdir():
    img4.append(cv2.imread(r"C:\Users\SSS\Desktop\opencv_task\4\{}".format(i)).flatten())
    data_four=pd.DataFrame({'array':img4,'label':4})
img4  

[array([215, 195, 190, ...,   0,   0,   0], dtype=uint8),
 array([215, 200, 184, ...,   0,   0,   4], dtype=uint8),
 array([215, 200, 184, ...,   0,   0,   4], dtype=uint8),
 array([215, 200, 184, ...,   0,   0,   4], dtype=uint8),
 array([207, 196, 182, ...,   0,   0,   0], dtype=uint8),
 array([207, 196, 182, ...,   0,   0,   0], dtype=uint8),
 array([207, 196, 182, ...,   0,   0,   0], dtype=uint8),
 array([213, 198, 189, ...,   0,   0,   3], dtype=uint8),
 array([213, 198, 189, ...,   0,   0,   3], dtype=uint8),
 array([213, 198, 189, ...,   0,   0,   3], dtype=uint8),
 array([209, 201, 184, ...,   1,   0,   4], dtype=uint8),
 array([209, 201, 184, ...,   1,   0,   4], dtype=uint8),
 array([209, 201, 184, ...,   1,   0,   4], dtype=uint8),
 array([211, 194, 185, ...,   0,   0,   0], dtype=uint8),
 array([211, 194, 185, ...,   0,   0,   0], dtype=uint8),
 array([209, 200, 187, ...,   0,   0,   0], dtype=uint8),
 array([209, 200, 187, ...,   0,   0,   0], dtype=uint8),
 array([209, 2

In [8]:
data_four

array  label
0   [215, 195, 190, 215, 195, 190, 213, 195, 188, ...      4
1   [215, 200, 184, 212, 199, 183, 210, 197, 183, ...      4
2   [215, 200, 184, 212, 199, 183, 210, 197, 183, ...      4
3   [215, 200, 184, 212, 199, 183, 210, 197, 183, ...      4
4   [207, 196, 182, 208, 197, 183, 210, 197, 183, ...      4
..                                                ...    ...
93  [206, 197, 187, 206, 197, 187, 207, 195, 183, ...      4
94  [206, 197, 187, 206, 197, 187, 207, 195, 183, ...      4
95  [206, 197, 187, 206, 197, 187, 207, 195, 183, ...      4
96  [215, 195, 190, 215, 195, 190, 213, 195, 188, ...      4
97  [215, 195, 190, 215, 195, 190, 213, 195, 188, ...      4

[98 rows x 2 columns]

In [ ]:
vid=cv2.VideoCapture(0)
count=0
while True:
    count=count+1
    su,img=vid.read()
    if su==True:
        cv2.imshow("video",img)
        images=cv2.imwrite(r"C:\Users\SSS\Desktop\opencv_task\5\{}.jpg".format(count),img)

    if cv2.waitKey(1)==ord("q"):
        break
cv2.destroyAllWindows()

In [5]:
os.chdir(r"C:\Users\SSS\Desktop\opencv_task\5")
img5=[]
for i in os.listdir():
    img5.append(cv2.imread(r"C:\Users\SSS\Desktop\opencv_task\5\{}".format(i)).flatten())
    data_five=pd.DataFrame({'array':img5,'label':5})
img5 

[array([169, 162, 143, ...,   0,   0,   0], dtype=uint8),
 array([169, 162, 143, ...,   0,   0,   0], dtype=uint8),
 array([178, 163, 144, ...,   0,   0,   0], dtype=uint8),
 array([178, 163, 144, ...,   0,   0,   0], dtype=uint8),
 array([178, 163, 144, ...,   0,   0,   0], dtype=uint8),
 array([177, 166, 146, ...,   0,   0,   0], dtype=uint8),
 array([177, 166, 146, ...,   0,   0,   0], dtype=uint8),
 array([177, 166, 146, ...,   0,   0,   0], dtype=uint8),
 array([178, 166, 148, ...,   0,   0,   0], dtype=uint8),
 array([178, 166, 148, ...,   0,   0,   0], dtype=uint8),
 array([188, 166, 148, ...,   0,   0,   0], dtype=uint8),
 array([188, 166, 148, ...,   0,   0,   0], dtype=uint8),
 array([188, 166, 148, ...,   0,   0,   0], dtype=uint8),
 array([191, 172, 145, ...,   0,   0,   0], dtype=uint8),
 array([191, 172, 145, ...,   0,   0,   0], dtype=uint8),
 array([191, 172, 145, ...,   0,   0,   0], dtype=uint8),
 array([187, 172, 140, ...,   0,   0,   0], dtype=uint8),
 array([187, 1

In [6]:
data_five

array  label
0   [169, 162, 143, 166, 159, 140, 163, 156, 137, ...      5
1   [169, 162, 143, 166, 159, 140, 163, 156, 137, ...      5
2   [178, 163, 144, 176, 161, 142, 171, 157, 138, ...      5
3   [178, 163, 144, 176, 161, 142, 171, 157, 138, ...      5
4   [178, 163, 144, 176, 161, 142, 171, 157, 138, ...      5
5   [177, 166, 146, 176, 165, 145, 172, 162, 144, ...      5
6   [177, 166, 146, 176, 165, 145, 172, 162, 144, ...      5
7   [177, 166, 146, 176, 165, 145, 172, 162, 144, ...      5
8   [178, 166, 148, 176, 164, 146, 176, 162, 144, ...      5
9   [178, 166, 148, 176, 164, 146, 176, 162, 144, ...      5
10  [188, 166, 148, 185, 163, 145, 184, 163, 142, ...      5
11  [188, 166, 148, 185, 163, 145, 184, 163, 142, ...      5
12  [188, 166, 148, 185, 163, 145, 184, 163, 142, ...      5
13  [191, 172, 145, 193, 174, 147, 185, 168, 142, ...      5
14  [191, 172, 145, 193, 174, 147, 185, 168, 142, ...      5
15  [191, 172, 145, 193, 174, 147, 185, 168, 142, ...      5
16  [187, 172, 140, 186, 171, 139, 182, 168, 139, ...      5
17  [187, 172, 140, 186, 171, 139, 182, 168, 139, ...      5
18  [187, 172, 140, 186, 171, 139, 182, 168, 139, ...      5
19  [187, 173, 150, 185, 171, 148, 184, 170, 147, ...      5
20  [187, 173, 150, 185, 171, 148, 184, 170, 147, ...      5
21  [187, 173, 150, 185, 171, 148, 184, 170, 147, ...      5
22  [180, 174, 151, 180, 174, 151, 179, 172, 152, ...      5
23  [180, 174, 151, 180, 174, 151, 179, 172, 152, ...      5
24  [180, 174, 151, 180, 174, 151, 179, 172, 152, ...      5
25  [186, 178, 155, 184, 176, 153, 183, 172, 150, ...      5
26  [186, 178, 155, 184, 176, 153, 183, 172, 150, ...      5
27  [186, 178, 155, 184, 176, 153, 183, 172, 150, ...      5
28  [188, 177, 157, 187, 176, 156, 184, 173, 151, ...      5
29  [186, 177, 157, 184, 175, 155, 182, 174, 151, ...      5
30  [186, 177, 157, 184, 175, 155, 182, 174, 151, ...      5
31  [191, 180, 160, 190, 179, 159, 187, 178, 158, ...      5
32  [191, 180, 160, 190, 179, 159, 187, 178, 158, ...      5
33  [191, 180, 160, 190, 179, 159, 187, 178, 158, ...      5
34  [192, 180, 162, 191, 179, 161, 187, 177, 159, ...      5
35  [192, 180, 162, 191, 179, 161, 187, 177, 159, ...      5
36  [192, 180, 162, 191, 179, 161, 187, 177, 159, ...      5
37  [190, 184, 161, 189, 183, 160, 188, 182, 159, ...      5
38  [190, 184, 161, 189, 183, 160, 188, 182, 159, ...      5
39  [190, 184, 161, 189, 183, 160, 188, 182, 159, ...      5
40  [196, 184, 166, 194, 182, 164, 192, 181, 161, ...      5
41  [196, 184, 166, 194, 182, 164, 192, 181, 161, ...      5
42  [196, 184, 166, 194, 182, 164, 192, 181, 161, ...      5
43  [197, 187, 169, 197, 187, 169, 198, 186, 168, ...      5
44  [197, 187, 169, 197, 187, 169, 198, 186, 168, ...      5
45  [197, 187, 163, 195, 185, 161, 191, 184, 157, ...      5
46  [197, 187, 163, 195, 185, 161, 191, 184, 157, ...      5
47  [197, 187, 163, 195, 185, 161, 191, 184, 157, ...      5
48  [204, 190, 168, 202, 189, 167, 200, 187, 165, ...      5
49  [204, 190, 168, 202, 189, 167, 200, 187, 165, ...      5
50  [204, 190, 168, 202, 189, 167, 200, 187, 165, ...      5
51  [210, 193, 167, 208, 191, 165, 208, 188, 163, ...      5
52  [210, 193, 167, 208, 191, 165, 208, 188, 163, ...      5
53  [210, 193, 167, 208, 191, 165, 208, 188, 163, ...      5
54  [201, 196, 171, 200, 195, 170, 199, 192, 167, ...      5

created array and label for one finger sign,two finger sign,three finger sign,four finger sign,five finger sign with label 1,2,3,4,5